### PR TITLE
data type changed

### PR DESCRIPTION
**Pull request by bsingh-nla**
@MingtaoSun , @danielbaker , @yetti can you please look.

### CODE REVIEW

**Comment by danielbaker** [comment]
What was the reasoning for this?

**Comment by terenceingram** [comment]
Temporary fix so that we can release Tarkine. We need to make this be a full release like amberdb instead of using snapshots @danielbaker

**Comment by bsingh-nla** [comment]
date in json is string. without this change conversion was failing and no data was display :disappointed:

**Comment by danielbaker** [comment]
:+1:

**Pull request merged**
