### PR TITLE
Bs dscs 1210 transcripts

### PR DESCRIPTION
**Pull request by bsingh-nla**
@scoen, @AaronCMuller , @yetti , @MingtaoSun can you please look.

### CODE REVIEW

**Comment by bsingh-nla** [comment]
sorry, forgot to add something

**Comment by bsingh-nla** [comment]
can you please look now.

**Comment by bsingh-nla** [comment]
@scoen, @AaronCMuller , @yetti , @MingtaoSun, @shuangzhou , @JonathanShaw , @danielbaker  comments?

**Comment by scoen** [comment]
Looks ok to me

**Pull request merged**
